### ISSUE TITLE
`brew install bendews/homebrew-tap/apw` failing

### ISSUE THREAD

**Issue by r0hin** [bendews/apw#6]
I'm running `brew install bendews/homebrew-tap/apw`:

```
==> Installing bendews/tap/apw
==> deno compile --allow-all --output /opt/homebrew/Cellar/apw/1.0.0/bin/apw src/cli.ts
Last 15 lines from /Users/rohin/Library/Logs/Homebrew/apw/01.deno:
  const status = error.code ? error.code : Status.GENERIC_ERROR;
                 ~~~~~
    at file:///private/tmp/apw-20241010-9826-2wbisk/src/cli.ts:170:18

TS18046 [ERROR]: 'error' is of type 'unknown'.
  const status = error.code ? error.code : Status.GENERIC_ERROR;
                              ~~~~~
    at file:///private/tmp/apw-20241010-9826-2wbisk/src/cli.ts:170:31

TS18046 [ERROR]: 'error' is of type 'unknown'.
    JSON.stringify({ error: error.message, status, results: [] }),
                            ~~~~~
    at file:///private/tmp/apw-20241010-9826-2wbisk/src/cli.ts:172:29

Found 3 errors.
```

Perhaps I am missing something? (MacOS Sequoia 15.0.1, Homebrew 4.4.0-119-g587949b)

Seems a random typescript issue.

**Comment by viktorshamal** [comment]
@r0hin #7 should be a fix if you want to build the project yourself 🙌

**Comment by bendews** [comment]
@r0hin I've pushed a hotfix for this issue, please try again and let me know 😄

**Comment by r0hin** [comment]
Nice! All working for me now (and the Raycast extension running locally)
